CREATE DATABASE IF NOT EXISTS cadprod;

USE cadprod;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE produtos (
		ID INT NOT NULL AUTO_INCREMENT,
		NOME VARCHAR(50),
		PRECO DECIMAL(15,5),
		DESCRICAO VARCHAR(1000),
        PRIMARY KEY (ID)
);
    